apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"web:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"web\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2022-10-12T12:12:08Z"
  generation: 2
  labels:
    app: "{{ .Release.Name }}"
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: web
  name: "{{ .Release.Name }}"
  namespace: test
  resourceVersion: "664719"
  uid: 288b7414-9bcc-41fb-adf7-f3a68bd15f1f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: web
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/test/web@sha256:983ff792ee82b7abcb38a41da3ac7a6198ee3844ba94b0329325a49448c5f941
        imagePullPolicy: IfNotPresent
        name: "{{ .Release.Name }}"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-10-12T12:12:32Z"
    lastUpdateTime: "2022-10-12T12:12:32Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-10-12T12:12:08Z"
    lastUpdateTime: "2022-10-12T12:12:32Z"
    message: ReplicaSet "web-7d95c65cf7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
