apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-10-12T13:45:42Z"
  labels:
    app: web
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: web
    app.kubernetes.io/managed-by: Helm
  name: "{{ .Release.Name }}"
  namespace: test
  resourceVersion: "683142"
  uid: 5871ba06-f4c3-4e1a-acfd-97cf4f36331a
spec:
  host: "{{ .Release.Name }}-test.apps.ocp4.example.com"
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: "{{ .Release.Name }}" 
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2022-10-12T13:45:42Z"
      status: "True"
      type: Admitted
    host: "{{ .Release.Name }}-test.apps.ocp4.example.com"
    routerCanonicalHostname: router-default.apps.ocp4.example.com
    routerName: default
    wildcardPolicy: None
